### ISSUE TITLE
建议：在序列化中添加binn序列化格式

### ISSUE THREAD

**Issue by kroggen** [jobbole/awesome-c-cn#5]
您可以在这里查看：

https://github.com/liteserver/binn

它也在：

https://notabug.org/koz.ross/awesome-c#serialization

**Comment by tangyouhua** [comment]
感谢提交建议资源，binn会加入观察列表，资源大全新加入资源star 300+

**Comment by kroggen** [comment]
我想这将是很好的，你的国家的许多人都知道，即使在到达300星之前。 反正，谢谢！

**Comment by tangyouhua** [comment]
感谢:)
